[build]
  publish = "dist/periodic-table/browser"
  command = "npm run build:prod"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
